[package]
name = "minisudo"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
rpassword = "7.2"
bcrypt = "0.17"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
